It 37074
apgsga-it/patchserver-setup pull request #24
Opened 2021-03-17 18:08 UTC by apgsga-uge

poor coding - no testing - but perhaps more or less in the correct plans?

2021-03-17 20:01 UTC, apgsga-jhe approved these changes
@apgsga-uge , @chhex 

With my poor Bolt/Puppet knowledge, I would say that it looks good, at least good enough for me to test it with the next installation ;)

2021-03-18 07:28 UTC, chhex requested changes
Coool

ok a couple of humble points and change requests / propositions: 

Just to get the intention of the code right:  

A Pipeline Jenkins Job is created with inlined Pipeline code, which runs at every 5th minute past every hour from 6 through 16 on every day-of-week from Monday through Friday. The inlined Pipeline code basically invokes a script, which 3? branches  for all Modules defined in DbModules.json. The scripts is processed as template and deployed with a plan.

Main points: 

- New code is alway effected by the existing code. The existing code of the jenkins_create_jobs plan isn't very maintainable and understandable . Realizing that while adding an additional Job to be created , i refactored the code of this plan quite a lot. I think the intention of code the should now be clearer. Also the code is organized in a way that the plan , upon running again , ignores the existing Jobs : https://github.com/apgsga-it/patchserver-setup/pull/23 This two pull requests will produce merge conflicts, which need to be resolved. This will also address some minor issues here. I would suggest to merge the pull  23 first and then adopt this one to the merged code base.

- The script location:  $home_dir is actually the home directory of the -u <user> with which bolt is executed on the target - the sudo user - and not jenkins home , like assumed, see Pipeline code (/var/lib/jenkins/apg-script). But i would suggest , that the script is actually deployed with the piper rpm and that the template processing is done in piper_service_properties.pp - where the property files are template processed. Ok the plan would need to be renamed. The ratio for putting it into the piper source base: It has very much to do with, the processing of piper. 
- Jenkins Plugins and Versions:  Plugins and Versions need to be aligned with what is deployed .. needs to be at least verified 

For the rest , see the inlined comments.

2021-03-18 07:35 UTC, chhex commented on plans/jenkins_create_jobs.pp
> +    $generic_builder_template = "/tmp/genericbuilder-config.xml"
This is where the Jenkins Job Xml File is copied to on the target machine as Input the Jenkins Cli create Job Command over ssh. I would use a new file and not reuse the one for the Generic Job Builder

2021-03-18 07:36 UTC, chhex commented on plans/jenkins_create_jobs.pp
> +    $generic_builder_cmd = "ssh -o \"StrictHostKeyChecking=no\" -l ${user}  -p ${targetall.vars[jenkins_cli_port]} localhost  create-job GenericPipelineJobBuilder < <(cat ${generic_builder_template})
We need here a new Job Name other the GenericPipelineJobBuidler ,otherwise the Jenkins Cli command will fail with Job already exists.

2021-03-18 07:37 UTC, chhex commented on plans/jenkins_dirs_create.pp
> +    file { $home_dir/apg-script:
As said in above, $home_dir is actually the home directory of the sudo user

2021-03-18 07:40 UTC, chhex commented on templates/branchWorkaround.sh.epp
> +  myTag=Ms_patch_$( expr ${myDiff} + $( ls -al /var/opt/apg-patch-service-server/db/Patch*.json | grep -iv log | cut -d '/' -f6 | cut -d 'h' -f2 | cut -d '.' -f1 | tail -n1 ))
Can't say really much here ....

2021-03-18 07:42 UTC, chhex commented on templates/runBranchWorkaround.xml.epp
> +<flow-definition plugin="workflow-job@2.40">
Not quite sure about the plugin version , need to check.

2021-03-18 07:43 UTC, chhex commented on templates/runBranchWorkaround.xml.epp
> +    <org.jenkinsci.plugins.pipeline.modeldefinition.actions.DeclarativeJobAction plugin="pipeline-model-definition@1.7.2"/>
Not quite sure if we have this plugin installed and which version

2021-03-18 07:44 UTC, chhex commented on templates/runBranchWorkaround.xml.epp
> +        def myRequest         =&quot;/var/lib/jenkins/apg-script/branchWorkaround.sh&quot;
As said : the location debate

2021-03-18 07:46 UTC, chhex commented on templates/runBranchWorkaround.xml.epp
> +        cron(&apos;*/5 6-16 * * 1-5&apos;)
A little confusing : the cron schedule is specified redundantly ... in the Job definition and in the Pipeline, intended?

2021-03-18 07:47 UTC, chhex commented on templates/runBranchWorkaround.xml.epp
> +  <definition class="org.jenkinsci.plugins.workflow.cps.CpsFlowDefinition" plugin="workflow-cps@2.83">
Need to check the version

2021-03-18 10:06 UTC, merged