IT-36769 / Patchserver Setup, Move Target, User , Password from inventory.yaml back to commandline
apgsga-it/patchserver-setup pull request #8
Opened 2021-01-26 12:32 UTC by apgsga-jhe

@chhex , @apgsga-uge

Here a pull request in order to prompt on command line for the following information:

- Target VM on which installations will be performed
- SSH User used to access the target VM
- SSH Password used to access the target VM

Regarding the access to git.apgsga.ch, I added a new property which would have to be changed before running any plan if we clone from git.apgsga.ch. Because the info is eventually needed in the ruby script (cloning repo is optional), I thought it's enough to provide the possibility to set a property, without always prompting for it.

2021-01-26 14:40 UTC, chhex reviewed
I would use the prompt plugin only for the target ssh user password 

And why not via command line?

Like, for example for the local target: 

`bolt plan run piper::cvs_install   --concurrency 10  --user che --targets jenkins-local,centpatch  --password-prompt ` 

And  for example a jenkins-t target: 

`bolt plan run piper::cvs_install   --concurrency 10  --user che --targets jenkins-t --password-prompt `

With a inventory file as follows (exerpt) : 

```
groups:
   - name: jenkins-local
     config:
        transport: ssh
     vars:
       # Local Test Vm specific configuration properties
        piper_bind_address:  # empty for local testing
        piper_cvs_remote_host: cvs-t.apgsga.ch
        piper_spring_profiles: live,remotecvs, patchOMock
       .....
   - name: jenkins-t
      targets:
        - uri: jenkins-t.apgsga.ch
          name:  jenkins-test
       config:
         transport: ssh
       vars:
         # Jenkins-t specific configurations
        piper_bind_address:  localhost
        piper_cvs_remote_host: cvs-t.apgsga.ch
        piper_spring_profiles: live,remotecvs, patchOMat
        ....
vars: 
 # Global configuration for all targets
  artifactory_uri: artifactory4t4apgsga.jfrog.io/artifactory
  artifactory_user: dev
.....
```

Naturally the script 

`./patchserver-setup.rb `

would need to be adopted accordingly  (...not really a big deal) 

Also i don't think prompt plugin is a general solution to avoid encrypted password storage? 

We need passwords - apart from target ssh user and the git user - for (at least): 

 piper_cvs_user: che # TODO (che, 7.1) -> svcCvsClient
 jenkins_ssh_user: che # TODO (che, 7.1)  -> apg-patch-service-server
  ...
 artifactory_user: # For accessing artifactory via piper and for the yum repo 

The later actually being stored on the target in the yum repo declaration: 

```
che@centpatch ~> more /etc/yum.repos.d/Apg-Piper-Yum.repo 
[Apg-Piper-Yum]
name=Apg Piper Repo
baseurl=https://ops-test:<somepassword>@artifactory4t4apgsga.jfrog.io/artifactory/multiservice_yumdev
enabled=1
gpgcheck=0
```

Currently <somepassword> is managed via Puppet Bolt Hierra

The piper_cvs_user and  jenkins_ssh_user passwords are currently the same as for ssh user for the target (jenkins-local)

The artifactory user for piper is stored encrypted in the inventory.yaml file.

  
  
@apgsga-jhe  @apgsga-uge

2021-01-27 04:31 UTC, apgsga-jhe commented
@chhex : Thanks for the feedback.

"_And why not via command line?_" : Because I didn't know how to be prompted by bolt without the _prompt plugin :) :) :) ..... But yeah, definitely what you suggested. I'll update the code accordingly and re-submit for review.

@apgsga-uge

2021-01-27 05:16 UTC, apgsga-jhe commented
@chhex , @apgsga-uge 

I made couple of changes based on Christoph's feedback. I also added the possibility to pass the git username via command line parameter. Here an example of how a plan would be started (-gu --> gitUser):

`./patchserver-setup.rb -i piper::java_install -u cm -t 192.168.159.130 -gu jhe`

2021-01-27 07:23 UTC, chhex submitted a review, later dismissed
@apgsga-jhe Cool, approved

2021-01-27 07:26 UTC, apgsga-jhe commented on inventory.yaml
> +        git:
@chhex : yes exactly , and this will be done within IT-36776

2021-01-27 17:48 UTC, chhex commented
@apgsga-jhe  As discussed both scenarios are possible: 

`bolt plan run piper::cvs_install --concurrency 10 --user che --targets jenkins-local,centpatch --password-prompt`

where jenkins-local corresponds to a group name in the inventory.yaml file 

```
groups:
   - name: jenkins-local
     config:
```

and centpatch to a concrete target uri.  Bolt basically merges the two.

And 

`bolt plan run piper::cvs_install --concurrency 10 --user che --targets jenkins-t --password-prompt`

Where jenkins-t corresponds a target group in the bolt inventory file:

```
groups:
   - name: jenkins-t
      targets:
        **- uri: jenkins-t.apgsga.ch**
          name:  jenkins-test
       config:
         transport: ssh

```

In this case there needs to be at least one uri specific in the group in the inventory.yaml file

2021-01-27 17:54 UTC, chhex requested changes
See comments above

2021-01-28 05:14 UTC, apgsga-jhe commented
@chhex : I made changes accordingly, we can now start a plan with for example:

`./patchserver-setup.rb -i piper::java_install -u cm -t testvms,192.168.159.130 -s`

Could you do a quick review again?

2021-01-28 09:52 UTC, chhex requested changes
@apgsga-jhe Sorrrrryyyyy, my fault:  rethinking , i would prefer as a temporary solution the gitUser option, but optional.... and if not present -u user. 
What do think? Small change...

2021-02-03 09:20 UTC, chhex commented
@apgsga-jhe  I going to merge this one, since according to IT-36770 decisions, the -u user is the same as for the git pull request. The cm user will be a predefined jenkins user. 

So the command will be something like: 

`./patchserver-setup.rb -i piper::java_install -u jhe -t testvms,192.168.159.130 -s`

@apgsga-uge  FYI

2021-02-03 09:20 UTC, merged

2021-02-03 09:54 UTC, chhex commented
@apgsga-jhe  @apgsga-uge  Sorry , this merge was to eager. Doesn't work.